### PR TITLE
refactor: change swappers permissions

### PR DESCRIPTION
**Pull request by 0xsambugs**
We are now making a small change. We are bringing back the "super admin role" so now everything is consistent with the rest of the permissioned contracts, and we are setting it as its own admin

### CODE REVIEW

**Review by 0xged — COMMENTED** [review]
I do understand consistency... But... `ADMIN_ROLE` here becomes completely pointless? We are having a `Governor` to appoint `Semi-governors` which do nothing. And a `Governor` that appoints `executors`. Not sure about this tbh. If you've got strong feelings about it, lets go, but it seems kinda circular.

**Comment by 0xsambugs** [comment]
> I do understand consistency... But... `ADMIN_ROLE` here becomes completely pointless? We are having a `Governor` to appoint `Semi-governors` which do nothing. And a `Governor` that appoints `executors`. Not sure about this tbh. If you've got strong feelings about it, lets go, but it seems kinda circular.

Damn, you are reviewing things too fast. The next PR will add a permissioned `sendDust` and `revokeAllowances`. The idea is that admins will have permissions over those

By doing so, we can have the msig on the super admin role, bots on the admin role, and swap executioners on their own role

**Review by 0xged — APPROVED** [review]
Woops! Sorry hehe. Then this is goo!

**Review by nchamo — APPROVED** [review]
I had the same question as @0xged , but I saw your response 👍

**Pull request merged**
